-- ========================================
-- EXTENSIONS
-- ========================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ========================================
-- TABLE: certificates
-- ========================================

CREATE TABLE public.certificates (
    id bigint NOT NULL,
    title text NOT NULL,
    subtitle text,
    image_url text,
    type text,
    proof_url text,
    start_date text,
    end_date text,
    status text,
    is_visible boolean DEFAULT true,
    is_featured boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now()
);

ALTER TABLE public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);

ALTER TABLE public.certificates
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: comments
-- ========================================

CREATE TABLE public.comments (
    id bigint NOT NULL,
    name text,
    comment text,
    image_url text,
    likes integer DEFAULT 0,
    is_pinned boolean DEFAULT false,
    replies jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    liked_by_admin boolean DEFAULT false
);

ALTER TABLE public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);

ALTER TABLE public.comments
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- TABLE: projects
-- ========================================

CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    live_url text,
    github_url text,
    technologies text[] DEFAULT '{}'::text[],
    key_features text[] DEFAULT '{}'::text[],
    image_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    image_urls jsonb DEFAULT '[]'::jsonb
);

ALTER TABLE public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

-- ========================================
-- TABLE: tech_stack
-- ========================================

CREATE TABLE public.tech_stack (
    id bigint NOT NULL,
    name text NOT NULL,
    logo_url text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.tech_stack
    ADD CONSTRAINT tech_stack_pkey PRIMARY KEY (id);

ALTER TABLE public.tech_stack
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX idx_projects_created_at
ON public.projects(created_at);

CREATE INDEX idx_comments_created_at
ON public.comments(created_at);

-- ========================================
-- ROW LEVEL SECURITY
-- ========================================

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_stack ENABLE ROW LEVEL SECURITY;

-- ========================================
-- POLICIES (OPEN PUBLIC ACCESS)
-- ========================================

CREATE POLICY "Allow public read projects"
ON public.projects
FOR SELECT
USING (true);

CREATE POLICY "Allow public insert comments"
ON public.comments
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Allow public read comments"
ON public.comments
FOR SELECT
USING (true);

CREATE POLICY "Allow public update comments"
ON public.comments
FOR UPDATE
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow public read certificates"
ON public.certificates
FOR SELECT
USING (true);

CREATE POLICY "Allow public read tech_stack"
ON public.tech_stack
FOR SELECT
USING (true);

-- ========================================
-- POLICIES (AUTHENTICATED WRITE ACCESS)
-- ========================================

CREATE POLICY "Allow authenticated insert projects"
ON public.projects
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated update projects"
ON public.projects
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated delete projects"
ON public.projects
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated insert certificates"
ON public.certificates
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated update certificates"
ON public.certificates
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated delete certificates"
ON public.certificates
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated insert tech_stack"
ON public.tech_stack
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow authenticated update tech_stack"
ON public.tech_stack
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated delete tech_stack"
ON public.tech_stack
FOR DELETE
TO authenticated
USING (true);

CREATE POLICY "Allow authenticated delete comments"
ON public.comments
FOR DELETE
TO authenticated
USING (true);

-- ========================================
-- UPDATED_AT TRIGGER
-- ========================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON public.projects
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- ========================================
-- SEED DATA
-- ========================================

-- Seed projects
INSERT INTO public.projects (id, title, description, live_url, github_url, technologies, key_features, image_url, image_urls)
VALUES (
    'f7a1b2c3-d4e5-4789-abcd-f9ebeca01234',
    'Rupee Matrix',
    'Rupee Matrix is a finance and investment platform focused on wealth management services including mutual funds, insurance, bonds, and retirement planning. Built with a responsive and user-friendly interface to simplify financial guidance, investment exploration, and service accessibility. Features structured service modules and information architecture designed to improve user engagement and financial decision support.',
    'https://rupeematrix.in',
    '',
    ARRAY['React.js', 'Node.js', 'JavaScript', 'CSS'],
    ARRAY[
        'Wealth management services for mutual funds, insurance, bonds & retirement planning',
        'Responsive user-friendly interface for simplified financial guidance',
        'Structured service modules & information architecture for engagement',
        'Investment exploration & service accessibility',
        'Financial decision support tools'
    ],
    '/images/rupee-matrix-placeholder.svg',
    '["/images/rupee-matrix-placeholder.svg"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    live_url = EXCLUDED.live_url,
    github_url = EXCLUDED.github_url,
    technologies = EXCLUDED.technologies,
    key_features = EXCLUDED.key_features,
    image_url = EXCLUDED.image_url,
    image_urls = EXCLUDED.image_urls;

-- Seed certificates
INSERT INTO public.certificates (id, title, subtitle, image_url, type, proof_url, start_date, end_date, status, is_visible, is_featured, created_at)
VALUES 
(
    1,
    'Meta Front-End Developer Professional Certificate',
    'Meta / Coursera',
    'https://images.credly.com/size/680x680/images/e91ed0b0-842b-417f-8d2f-b07e52cc85a1/image.png',
    'course',
    'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    '2025-09-15',
    '2026-03-15',
    'Completed',
    true,
    true,
    '2026-03-15 00:00:00'
),
(
    2,
    'Smart India Hackathon 2025 — Winner',
    'Ministry of Education, Govt. of India',
    'https://upload.wikimedia.org/wikipedia/en/2/29/Smart_India_Hackathon_logo.png',
    'achievement',
    '',
    '2025-12-08',
    '2025-12-10',
    'Completed',
    true,
    true,
    '2025-12-10 00:00:00'
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    image_url = EXCLUDED.image_url,
    type = EXCLUDED.type,
    proof_url = EXCLUDED.proof_url,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    status = EXCLUDED.status,
    is_visible = EXCLUDED.is_visible,
    is_featured = EXCLUDED.is_featured,
    created_at = EXCLUDED.created_at;

-- Seed tech_stack
INSERT INTO public.tech_stack (id, name, logo_url)
VALUES
(1, 'React', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg'),
(2, 'Next.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg'),
(3, 'TypeScript', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg'),
(4, 'Tailwind CSS', 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg'),
(5, 'Node.js', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg'),
(6, 'PostgreSQL', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg'),
(7, 'Prisma', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prisma/prisma-original.svg'),
(8, 'Git', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg'),
(9, 'Supabase', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg'),
(10, 'Redux', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg'),
(11, 'GraphQL', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg'),
(12, 'Docker', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    logo_url = EXCLUDED.logo_url;